<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pm" nsURI="http://www.example.org/pm" nsPrefix="pm">
  <eClassifiers xsi:type="ecore:EClass" name="Employee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualification" lowerBound="1"
        eType="#//Qualification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participantProjects" upperBound="-1"
        eType="#//Project" eOpposite="#//Project/participants"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="managerProjects" upperBound="-1"
        eType="#//Project" eOpposite="#//Project/manager"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Task" eOpposite="#//Task/executor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="planTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" lowerBound="1"
        eType="#//Priority"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" lowerBound="1"
        eType="#//Project" eOpposite="#//Project/tasks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executor" eType="#//Employee"
        eOpposite="#//Employee/tasks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Task"
        eOpposite="#//Task/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Task" eOpposite="#//Task/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="closed" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participants" lowerBound="1"
        upperBound="-1" eType="#//Employee" eOpposite="#//Employee/participantProjects"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="manager" lowerBound="1"
        eType="#//Employee" eOpposite="#//Employee/managerProjects"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Task" eOpposite="#//Task/project"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Qualification">
    <eLiterals name="novice" literal="novice"/>
    <eLiterals name="programmer" value="1" literal="programmer"/>
    <eLiterals name="lead" value="2" literal="lead"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Priority">
    <eLiterals name="low" literal="low"/>
    <eLiterals name="medium" value="1"/>
    <eLiterals name="high" value="2" literal="high"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1"
        eType="#//Project" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employees" upperBound="-1"
        eType="#//Employee" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Task" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
